version: '3.5'
services:

  swagger-ui:
    build: swagger-ui
    image: fitness_swagger-ui
    ports:
      - "81:8080"
    networks:
      - fitness_ntwrk

  product-service:
    build: product_and_user-service
    image: product_and_user-service:1.0.0
    networks:
      - fitness_ntwrk
  audit-service:
    build: audit-service
    image: audit-service:1.0.0
    ports:
      - "8081:8081"
    networks:
      - fitness_ntwrk
  proxy:
    build: proxy
    image: fitness_proxy
    ports:
      - "80:80"
    networks:
      - fitness_ntwrk
networks:
  fitness_ntwrk:
    name: fitness_ntwrk