version: '3.8'
services:
  db:
    container_name: pg_container_MyFit
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container_MyFit
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: P112148s
    ports:
      - "5050:80"