version: '3.8'
services:
  db:
    container_name: pg_container_MyFit
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container_MyFit
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: P112148s
    ports:
      - "5050:80"
  mongodb:
    container_name: mongo_MyFit
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: auth
    ports:
      - '27017:27017'
  mongo-express:
    container_name: mongo_express_MyFit
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo_MyFit
      ME_CONFIG_BASICAUTH_USERNAME: admin@admin.com
      ME_CONFIG_BASICAUTH_PASSWORD: M112148o
    ports:
      - '8888:8081'