openapi: 3.0.0
info:
  version: 1.0.0
  title: Сервис журнала питания
  contact:
    name: ITAcademy
    url: http://it-academy.by

servers:
  - url: http://{host}:{port}
    description: custom server
    variables:
      host:
        description: host name
        default: localhost
      port:
        description: port value
        default: "8080"

tags:
  - name: "Безопасность"

paths:
  /api/v1/audit:
    get:
      tags:
        - "Безопасность"
      summary: "Получить страницу действий в системе"
      security:
        - bearerAuth: [ROLE_ADMIN]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Номер страницы
          required: false
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            default: 20
          description: Размер страницы
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfAudit'
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
  /api/v1/audit/{uuid}:
    get:
      tags:
        - "Безопасность"
      summary: "Получить информацию о действии в системе"
      security:
        - bearerAuth: [ROLE_ADMIN]
      parameters:
        - in: path
          name: uuid
          description: "Идентификатор пользователя"
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Audit'
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Bad_Request:
      description: Запрос некорректен. Сервер не может обработать запрос
      content:
        application/json:
          schema:
            oneOf:
              - type: array
                items:
                  $ref: '#/components/schemas/t_single_error_response'
              - $ref: '#/components/schemas/t_multiple_error_response'
          examples:
            t_single_error_response:
              value:
                - logref: error
                  message:  Запрос содержит некорретные данные. Измените запрос и отправьте его ещё раз
            t_multiple_error_response:
              value:
                logref: structured_error
                errors:
                  - field: time_unit
                    message: Поле должно быть положительным числом
    Unauthorized:
      description: Для выполнения запроса на данный адрес требуется передать токен авторизации
    Forbidden:
      description: Данному токенту авторизации запрещено выполнять запроса на данный адрес
    Internal_Server_Error:
      description: Внутренняя ошибка сервера. Сервер не смог корректно обработать запрос
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/t_single_error_response'
          example:
            - logref: error
              message:  Сервер не смог корректно обработать запрос. Пожалуйста обратитесь к администратору
  schemas:
    UserRole:
      type: string
      description: |
        Роль пользователя:
          * `ADMIN` - Администратор
          * `USER` - Пользователь
      enum:
        - "ADMIN"
        - "USER"
    UserStatus:
      type: string
      description: |
        Статус пользователя:
          * `WAITING_ACTIVATION` - Ожидает активации
          * `ACTIVATED` - Активирован
          * `DEACTIVATED` - Деактивирован
      enum:
        - "WAITING_ACTIVATION"
        - "ACTIVATED"
        - "DEACTIVATED"
    User:
      type: object
      description: Пользователь
      allOf:
        - $ref: '#/components/schemas/t_base_essence'
      properties:
        mail:
          type: string
          description: "Электронная почта"
        nick:
          type: string
          description: "Псевдоним"
        role:
          $ref: '#/components/schemas/UserRole'
        status:
          $ref: '#/components/schemas/UserStatus'
    EssenceType:
      type: string
      description: |
        Тип сущности:
          * `PRODUCT` - Продукт
          * `RECIPE` - Рецепт
          * `USER` - Пользователь
          * `JOURNAL_FOOD` - Журнал питания
          * `REPORT` - Отчёт
      enum:
        - "PRODUCT"
        - "RECIPE"
        - "USER"
        - "JOURNAL_FOOD"
        - "REPORT"
    Audit:
      type: object
      description: Информация о действии в системе
      properties:
        user:
          $ref: '#/components/schemas/User'
        text:
          type: string
          description: "Описание действия пользователя"
          example: "Создана запись в журнале питания"
        type:
          $ref: '#/components/schemas/EssenceType'
        id:
          type: string
          description: "Идентификатор сущности указанного типа"

    PageOfAudit:
      type: object
      description: Страница пользователей
      allOf:
        - $ref: '#/components/schemas/t_page'
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Audit'
        
    t_base_essence:
      type: object
      description: Описание базовой сущности.
      required:
        - uuid
        - dt_create
        - dt_update
      properties:
        uuid:
          description: Уникальный идентификатор сущности
          type: string
          format: uuid
          readOnly: true
        dt_create:
          description: Дата создания сущности (linux time)
          type: number
          format: int64
          readOnly: true
        dt_update:
          description: Дата последнего обновления сущности (linux time)
          type: integer
          format: int64
          readOnly: true

    t_page:
      type: object
      required:
        - number
        - size
        - total_pages
        - total_elements
        - content
        - first
        - number_of_elements
        - last
      description: Страница
      properties:
        number:
          type: integer
          description: Номер страницы
        size:
          description: Размер страницы
          type: integer
        total_pages:
          description: Количество страниц
          type: integer
        total_elements:
          description: Количество записей
          type: integer
        first:
          description: Признак является ли элемент первым
          type: boolean
        number_of_elements:
          description: Номер элемента
          type: integer
        last:
          description: Признак является ли элемент последним
          type: boolean

    t_single_error_response:
      type: object
      description: Ошибка. Содержит общее описание ошибки
      required:
        - logref
        - message
      properties:
        logref:
          type: string
          description: Тип ошибки
          example: error
        message:
          description: Сообщение ошибки
          type: string
          example: Запрос содержит некорретные данные. Измените запрос и отправьте его ещё раз

    t_multiple_error_response:
      type: object
      description: Ошибка. Содержит описание ошибок со ссылками на поля сущности
      required:
        - logref
        - errors
      properties:
        logref:
          type: string
          description: Тип ошибки
        errors:
          description: Наименование ошибочного поля
          type: array
          items:
            type: object
            properties:
              message:
                type: string
                description: Сообщение об ошибке
                example: Поле должно быть положительным числом
              field:
                type: string
                description: Наименование ошибочного поля
                example: time_unit